name: React CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Deploy to IIS
        shell: powershell
        run: |
          $destination = "C:\Kaushik\website\reactapp"

          # Remove old files (except web.config)
          Get-ChildItem $destination -Exclude "web.config" | Remove-Item -Recurse -Force

          # Copy new build
          Copy-Item "dist\*" $destination -Recurse -Force